### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by janacm** [ShivanKaul/SidebarOverflow#6]
Been using the extension happily for a few months now - but it seems to have stopped working recently. 

How can I help debug this issue? I'm on Windows 10, latest version of Chrome.

**Comment by ejlofgren** [comment]
This pull request should fix the issue: https://github.com/ShivanKaul/SidebarOverflow/pull/7

Until this PR is potentially accepted and the extension republished. You can run it locally by following instructions like https://superuser.com/questions/247651/how-does-one-install-an-extension-for-chrome-browser-from-the-local-file-system/247654#247654 and then change that line of code.

**Comment by ShivanKaul** [comment]
@janacm I merged in a couple of PRs. Can you confirm that it works for you now?

**Comment by janacm** [comment]
Looks good, thanks all!
